PICARD-1261: Use tag.startswith instead of accessing the first character by index
In PICARD-1261, the following error happened:

[...]
File "C:\Users\Admin\AppData\Local\MusicBrainz\Picard\plugins\keep.zip\keep.py", line 29, in keep
not tag[0] == "~"):
IndexError: string index out of range

Apparently, tag names can be completely empty. Use tag.startswith which deals
with this case correctly.