PICARD-747: use new QFileDialog.getSaveFileNameAndFilter()
It was broken by the move to PyQt api version 2, QString cannot be used.
Instead of a mutable string parameter, new methode returns a tuple.

It fixes:
selected_format = QtCore.QString()
AttributeError: 'module' object has no attribute 'QString'