.github/workflows/test: Disable py3.5
`actions/setup-python@v1` is no longer available with py3.5
as of 2022-01-29

Fixes:
```
Error: Version 3.5 with arch x64 not found
Available versions:
2.7.18 (x64)
3.10.2 (x64)
3.6.15 (x64)
3.7.12 (x64)
3.8.12 (x64)
3.9.10 (x64)
```